from django.urls import path
from.import views

app_name = 'navigation'

urlpatterns = [
    path('navigation/', views.mainpage, name="mainpage"),
    path('about/', views.about, name='about'),
    path('item/', views.item_something, name='item'),
    path('createitem/', views.createitem, name='createitem'),
    path('<int:id>/', views.update_item, name='updateitem'),
    path('view/<int:id>/', views.view_item, name='viewitem'),
    path('delete/<int:id>/', views.delete_item, name='deleteitem'),
    path('vendor/', views.vendor_something, name='vendor'),
    path('createvendor/', views.createvendor, name='createvendor'),
    path('edit/<int:id>/', views.update_vendor, name='updatevendor'),
    path('viewvendor/<int:id>/', views.view_vendor, name='viewvendor'),
    path('deletevendor/<int:id>/', views.delete_vendor, name='deletevendor'),
    path('purchase/', views.purchase, name='purchase'),
    path('createpurchase/', views.createpurchase, name='createpurchase'),
    path('deletepurchase/<int:id>/', views.delete_purchase, name='deletepurchase'),
    path('viewpurchase/<int:id>/', views.view_purchase, name='viewpurchase'), 
    path('updatepurchase/<int:id>/', views.update_purchase, name='updatepurchase'),  
    path('Stock/', views.stock, name='stock'),
    path('payment/', views.pamentvoucher, name='payment'),
    path('createpayment/', views.createpayment, name='createpayment'),
    path('deletepayment/<int:id>/', views.delete_paymentvoucher, name='deletepayment'),
    path('viewpayment/<int:id>/', views.view_paymentvoucher, name='viewpayment'),
    path('updatepayment/<int:id>/', views.update_paymentvoucher, name='updatepayment'),
    path('customer/', views.customer_something, name='customer'),
    path('createcustomer/', views.createcustomer, name='createcustomer'),
    path('editcusto/<int:id>/', views.update_customer, name='updatecustomer'),
    path('viewcusto/<int:id>/', views.view_customer, name='viewcustomer'),
    path('deletecustomer/<int:id>/', views.delete_customer, name='deletecustomer'),
    path('viewpricing/<int:id>/', views.view_pricing, name='viewpricing'),
    path('pricing/', views.pricing, name='pricing'),
    path('createpricing/',views.createpricing,name='createpricing'),
    path('deletpricing/<int:id>/', views.delete_pricing, name='deletpricing'),
    path('updatepricing/<int:id>/', views.update_pricing, name='updatepricing'), 
    path('sales/', views.sales, name='sales'),
    path('createsales/', views.createsalse, name='createsalse'),
    path('deletsalse/<int:id>/', views.delete_salse, name='deletsalse'),
    path('viewsalse/<int:id>/', views.view_salse, name='viewsalse'),
    path('updatesalse/<int:id>/', views.update_salse, name='updatesalse'), 
    path('gst/', views.gst, name='gst'),
    path('export/',views.export_users_xls,name='export'),
    path('gstexport/',views.export_gst_xls,name='gstexport'),
    #  path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAXajax_pricingscheme_load
    path('ajax/load-vcode/',views.loadvcode,name='ajax_vcode_load'),#ajax_customer_load
    path('ajax/load-icode/',views.loaditemcode,name='ajax_itemcode_load'),
    path('ajax/load-cname/',views.loadcustomerid,name='ajax_customer_load'),
    path('ajax/load-pricingscheme/',views.loadpricingscheme,name='ajax_pricingscheme_load'),
    path('ajax/load-batchno/',views.loadbatcno,name='ajax_batchno_load'),
]